src/Geta.NotFoundHandler.Admin/Areas/GetaNotFoundHandlerAdmin/Pages/Administer.cshtml.cs
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml;
using CsvHelper;
using Geta.NotFoundHandler.Admin.Pages.Geta.NotFoundHandler.Admin.Components.Card;
using Geta.NotFoundHandler.Admin.Pages.Geta.NotFoundHandler.Admin.Infrastructure;
using Geta.NotFoundHandler.Core.Redirects;
using Geta.NotFoundHandler.Core.Suggestions;
using Geta.NotFoundHandler.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Geta.NotFoundHandler.Admin.Pages.Geta.NotFoundHandler.Admin;

[Authorize(Constants.PolicyName)]
public class AdministerModel : PageModel
{
    private readonly IRedirectsService _redirectsService;
    private readonly ISuggestionService _suggestionService;
    private readonly RedirectsXmlParser _redirectsXmlParser;
    private readonly RedirectsCsvParser _redirectsCsvParser;
    private readonly RedirectsTxtParser _redirectsTxtParser;

    public AdministerModel(
        IRedirectsService redirectsService,
        ISuggestionService suggestionService,
        RedirectsXmlParser redirectsXmlParser,
        RedirectsCsvParser redirectsCsvParser,
        RedirectsTxtParser redirectsTxtParser)
    {
        _redirectsService = redirectsService;
        _suggestionService = suggestionService;
        _redirectsXmlParser = redirectsXmlParser;
        _redirectsCsvParser = redirectsCsvParser;
        _redirectsTxtParser = redirectsTxtParser;
    }

    [BindProperty(SupportsGet = true)]
    public string Message { get; set; }

    [BindProperty(SupportsGet = true)]
    public CardType CardType { get; set; }

    [BindProperty]
    public DeleteSuggestionsModel DeleteSuggestions { get; set; } = new DeleteSuggestionsModel();

    [BindProperty]
    public IFormFile ImportFile { get; set; }

    public IActionResult OnPostDeleteAllIgnoredSuggestions()
    {
        var count = _redirectsService.DeleteAllIgnored();

        return BuildResponse($"All {count} ignored suggestions permanently removed", CardType.Success);
    }

    public IActionResult OnPostDeleteAllSuggestions()
    {
        _suggestionService.DeleteAll();

        return BuildResponse("Suggestions successfully deleted", CardType.Success);
    }

    public IActionResult OnPostDeleteAllRedirects()
    {
        _redirectsService.DeleteAll();

        return BuildResponse("Redirects successfully deleted", CardType.Success);
    }

    public IActionResult OnPostDeleteSuggestions()
    {
        if (!ModelState.IsValid) return Page();

        _suggestionService.Delete(DeleteSuggestions.MaxErrors, DeleteSuggestions.MinimumDays);

        return BuildResponse("Suggestions successfully deleted", CardType.Success);
    }

    public IActionResult OnPostImportRedirects()
    {
        if (ImportFile == null)
        {
            return BuildResponse("The uploaded file is not a valid XML or CSV file. Please upload a valid XML/CSV file.",
                                 CardType.Warning);
        }

        if (ImportFile.IsXml())
        {
            return ProcessFile(_redirectsXmlParser);
        }

        if (ImportFile.IsCsv())
        {
            return ProcessFile(_redirectsCsvParser);
        }

        return BuildResponse("The uploaded file is not a valid. Please upload a file.",
                             CardType.Warning);
    }

    public IActionResult OnPostImportDeletedRedirects()
    {
        if (ImportFile == null || !ImportFile.IsTxt())
        {
            return BuildResponse("The uploaded file is not a valid TXT file. Please upload a valid TXT file.", CardType.Warning);
        }

        return ProcessFile(_redirectsTxtParser);
    }

    public IActionResult OnPostExportRedirects(string typeId)
    {
        if (string.IsNullOrEmpty(typeId))
        {
            return BuildResponse("Failed to Export", CardType.Warning);
        }

        var redirects = _redirectsService.GetSaved().ToList();

        if (!redirects.Any())
        {
            return BuildResponse("Nothing to Export", CardType.Warning);
        }

        return typeId.ToLower() switch
        {
            "xml" => ExportAsXml(redirects),
            "csv" => ExportAsCsv(redirects),
            _ => BuildResponse("Failed to export. Unsupported export type", CardType.Warning)
        };
    }

    private IActionResult ExportAsXml(List<CustomRedirect> redirects)
    {
        var document = _redirectsXmlParser.Export(redirects);

        using var memoryStream = new MemoryStream();
        using var writer = new XmlTextWriter(memoryStream, Encoding.UTF8) { Formatting = Formatting.Indented };
        document.WriteTo(writer);
        writer.Flush();
        memoryStream.Seek(0, SeekOrigin.Begin);

        return File(memoryStream.ToArray(), "text/xml", "customRedirects.xml");
    }

    private IActionResult ExportAsCsv(List<CustomRedirect> redirects)
    {
        var documents = _redirectsCsvParser.Export(redirects);

        using var memoryStream = new MemoryStream();
        using (var tw = new StreamWriter(memoryStream, leaveOpen: true))
        using (var csv = new CsvWriter(tw, CultureInfo.InvariantCulture))
        {
            csv.WriteRecords(documents);
        }

        memoryStream.Seek(0, SeekOrigin.Begin);
        return File(memoryStream.ToArray(), "text/csv", "customRedirects.csv");
    }

    private IActionResult BuildResponse(string message, CardType cardType)
    {
        Message = message;
        CardType = cardType;

        return RedirectToPage(new { Message, CardType });
    }

    private IActionResult ProcessFile(IRedirectsParser parser)
    {
        var redirects = parser.LoadFromStream(ImportFile.OpenReadStream());

        if (redirects.Any())
        {
            _redirectsService.AddOrUpdate(redirects);

            return BuildResponse($"{redirects.Count()} urls successfully imported.", CardType.Success);
        }

        return BuildResponse("No redirects could be imported", CardType.Warning);
    }
}

public class DeleteSuggestionsModel
{
    public int MaxErrors { get; set; } = 5;
    public int MinimumDays { get; set; } = 30;
}

src/Geta.NotFoundHandler.Admin/Areas/GetaNotFoundHandlerAdmin/Pages/Components/Card/CardViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Geta.NotFoundHandler.Admin.Pages.Geta.NotFoundHandler.Admin.Components.Card
{
    public class CardViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(string message, CardType cardType)
        {
            return View(new CardViewModel { Message = message, CardType = cardType });
        }
    }
}

src/Geta.NotFoundHandler.Admin/Areas/GetaNotFoundHandlerAdmin/Pages/Components/CheckboxReadonly/CheckboxReadonlyViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Geta.NotFoundHandler.Admin.Pages.Geta.NotFoundHandler.Admin.Components.CheckboxReadonly
{
    public class CheckboxReadonlyViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(bool isChecked)
        {
            return View(new CheckboxReadonlyViewModel { IsChecked = isChecked });
        }
    }
}

src/Geta.NotFoundHandler.Admin/Areas/GetaNotFoundHandlerAdmin/Pages/Components/SortableHeader/SortableHeaderViewComponent.cs
using Geta.NotFoundHandler.Data;
using Microsoft.AspNetCore.Mvc;

namespace Geta.NotFoundHandler.Admin.Areas.GetaNotFoundHandlerAdmin.Pages.Components.SortableHeader
{
    public class SortableHeaderViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(string displayName, string internalName, QueryParams @params, string additionalClass = null)
        {
            return View(new SortableHeaderViewModel(displayName, internalName, @params, additionalClass));
        }
    }
}

src/Geta.NotFoundHandler.Admin/Areas/GetaNotFoundHandlerAdmin/Pages/Components/SortableHeaderCell/SortableHeaderCellViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Geta.NotFoundHandler.Admin.Areas.GetaNotFoundHandlerAdmin.Pages.Components.SortableHeaderCell;

public class SortableHeaderCellViewComponent : ViewComponent
{
    private readonly IHttpContextAccessor _contextAccessor;

    public SortableHeaderCellViewComponent(IHttpContextAccessor contextAccessor)
    {
        _contextAccessor = contextAccessor;
    }

    public IViewComponentResult Invoke(string key, string displayName)
    {
        var context = _contextAccessor.HttpContext;

        return View(new SortableHeaderCellViewModel
        {
            QueryString = context?.Request.QueryString.ToString(),
            Key = key,
            DisplayName = displayName
        });
    }
}

src/Geta.NotFoundHandler.Admin/Areas/GetaNotFoundHandlerAdmin/Pages/Deleted.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Geta.NotFoundHandler.Admin.Areas.GetaNotFoundHandlerAdmin.Pages.Base;
using Geta.NotFoundHandler.Admin.Areas.GetaNotFoundHandlerAdmin.Pages.Extensions;
using Geta.NotFoundHandler.Admin.Areas.GetaNotFoundHandlerAdmin.Pages.Models;
using Geta.NotFoundHandler.Admin.Pages.Geta.NotFoundHandler.Admin.Models;
using Geta.NotFoundHandler.Core.Redirects;
using Geta.NotFoundHandler.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace Geta.NotFoundHandler.Admin.Pages.Geta.NotFoundHandler.Admin;

[Authorize(Constants.PolicyName)]
public class DeletedModel : AbstractSortablePageModel
{
    private readonly IRedirectsService _redirectsService;

    public DeletedModel(IRedirectsService redirectsService)
    {
        _redirectsService = redirectsService;
    }

    public string Message { get; set; }

    public IPagedList<CustomRedirect> Items { get; set; } = Enumerable.Empty<CustomRedirect>().ToPagedList();

    [BindProperty]
    public DeletedRedirectModel DeletedRedirect { get; set; }

    [BindProperty(SupportsGet = true)]
    public Paging Paging { get; set; }

    public void OnGet(string sortColumn, SortDirection? sortDirection)
    {
        ApplySort(sortColumn, sortDirection);

        Load();
    }

    public IActionResult OnPostCreate()
    {
        if (!ModelState.IsValid)
        {
            Load();
            return Page();
        }

        _redirectsService.AddDeletedRedirect(DeletedRedirect.OldUrl);

        return RedirectToPage();
    }

    public IActionResult OnPostDelete(string oldUrl)
    {
        _redirectsService.DeleteByOldUrl(oldUrl);
        return RedirectToPage();
    }

    private void Load()
    {
        var items = FindRedirects().ToPagedList(Paging.PageNumber, Paging.PageSize);
        Message =
            $"There are currently {items.TotalItemCount} URLs that return a Deleted response. This tells crawlers to remove these URLs from their index.";
        Items = items;
    }
    
    private IEnumerable<CustomRedirect> FindRedirects()
    {
        return _redirectsService
            .GetDeleted()
            .Sort(SortColumn, SortDirection);
    }
}

src/Geta.NotFoundHandler.Admin/Areas/GetaNotFoundHandlerAdmin/Pages/Ignored.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Geta.NotFoundHandler.Admin.Areas.GetaNotFoundHandlerAdmin.Pages.Base;
using Geta.NotFoundHandler.Admin.Areas.GetaNotFoundHandlerAdmin.Pages.Extensions;
using Geta.NotFoundHandler.Admin.Areas.GetaNotFoundHandlerAdmin.Pages.Models;
using Geta.NotFoundHandler.Admin.Pages.Geta.NotFoundHandler.Admin.Models;
using Geta.NotFoundHandler.Core.Redirects;
using Geta.NotFoundHandler.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace Geta.NotFoundHandler.Admin.Pages.Geta.NotFoundHandler.Admin;

[Authorize(Constants.PolicyName)]
public class IgnoredModel : AbstractSortablePageModel
{
    private readonly IRedirectsService _redirectsService;

    public IgnoredModel(IRedirectsService redirectsService)
    {
        _redirectsService = redirectsService;
    }

    public string Message { get; set; }

    public IPagedList<CustomRedirect> Items { get; set; } = Enumerable.Empty<CustomRedirect>().ToPagedList();

    [BindProperty(SupportsGet = true)]
    public Paging Paging { get; set; }

    public void OnGet(string sortColumn, SortDirection? sortDirection)
    {
        ApplySort(sortColumn, sortDirection);

        Load();
    }

    public IActionResult OnPostUnignore(string oldUrl)
    {
        _redirectsService.DeleteByOldUrl(oldUrl);

        return RedirectToPage();
    }

    private void Load()
    {
        var items = FindRedirects().ToPagedList(Paging.PageNumber, Paging.PageSize);
        Message = $"There are currently {items.TotalItemCount} ignored suggestions stored.";
        Items = items;
    }

    private IEnumerable<CustomRedirect> FindRedirects()
    {
        return _redirectsService
            .GetIgnored()
            .Sort(SortColumn, SortDirection);
    }
}

src/Geta.NotFoundHandler.Admin/Areas/GetaNotFoundHandlerAdmin/Pages/Index.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Geta.NotFoundHandler.Admin.Areas.GetaNotFoundHandlerAdmin.Pages.Base;
using Geta.NotFoundHandler.Admin.Areas.GetaNotFoundHandlerAdmin.Pages.Extensions;
using Geta.NotFoundHandler.Admin.Areas.GetaNotFoundHandlerAdmin.Pages.Models;
using Geta.NotFoundHandler.Admin.Areas.GetaNotFoundHandlerAdmin.Pages;
using Geta.NotFoundHandler.Admin.Pages.Geta.NotFoundHandler.Admin.Models;
using Geta.NotFoundHandler.Core.Redirects;
using Geta.NotFoundHandler.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace Geta.NotFoundHandler.Admin.Pages.Geta.NotFoundHandler.Admin;

[Authorize(Constants.PolicyName)]
public class IndexModel : AbstractSortablePageModel
{
    private readonly IRedirectsService _redirectsService;

    public IndexModel(IRedirectsService redirectsService)
    {
        _redirectsService = redirectsService;
    }

    public string Message { get; set; }

    public IPagedList<CustomRedirect> Items { get; set; } = Enumerable.Empty<CustomRedirect>().ToPagedList();

    [BindProperty(Name = nameof(CustomRedirect))]
    public RedirectModel CustomRedirect { get; set; }

    [BindProperty(Name = nameof(EditRedirect))]
    public RedirectModel EditRedirect { get; set; }

    [BindProperty(SupportsGet = true)]
    public Paging Paging { get; set; }

    [BindProperty(SupportsGet = true, Name = "q")]
    public string Query { get; set; }

    public bool HasQuery => !string.IsNullOrEmpty(Query);

    public void OnGet(RedirectsRequest request, string sortColumn, SortDirection? sortDirection)
    {
        ApplyRequest(request);
        ApplySort(sortColumn, sortDirection);

        Load();
    }

    public IActionResult OnPostCreate()
    {
        ModelState.RemoveNestedKeys(nameof(EditRedirect));

        if (ModelState.IsValid)
        {
            var customRedirect = new CustomRedirect(CustomRedirect.OldUrl,
                                                    CustomRedirect.NewUrl,
                                                    CustomRedirect.WildCardSkipAppend,
                                                    CustomRedirect.RedirectType);

            _redirectsService.AddOrUpdate(customRedirect);

            return RedirectToPage();
        }

        Load();
        return Page();
    }

    public IActionResult OnPostDelete(RedirectsRequest request)
    {
        ModelState.Clear();

        if (request.Id != null)
        {
            _redirectsService.DeleteById(request.Id.Value);
        }

        ApplyRequest(request);

        Load();

        return RedirectToPage(request);
    }

    public IActionResult OnPostUpdate(RedirectsRequest request)
    {
        ModelState.RemoveNestedKeys(nameof(CustomRedirect));
        
        if (ModelState.IsValid && EditRedirect.Id != null)
        {
            _redirectsService.AddOrUpdate(new CustomRedirect
            {
                Id = EditRedirect.Id,
                OldUrl = EditRedirect.OldUrl,
                RedirectType = EditRedirect.RedirectType,
                NewUrl = EditRedirect.NewUrl,
                WildCardSkipAppend = EditRedirect.WildCardSkipAppend
            });

            return RedirectToPage(request);
        }

        Load();
        return Page();
    }

    private void Load()
    {
        var items = FindRedirects().ToPagedList(Paging.PageNumber, Paging.PageSize);
        Message = $"There are currently stored {items.TotalItemCount} custom redirects.";
        Items = items;
    }

    private IEnumerable<CustomRedirect> FindRedirects()
    {
        var result = HasQuery ? _redirectsService.Search(Query) : _redirectsService.GetSaved();

        return result
            .Sort(SortColumn, SortDirection);
    }

    private void ApplyRequest(RedirectsRequest request)
    {
        if (request.PageNumber.HasValue)
        {
            Paging.PageNumber = request.PageNumber.Value;
        }

        Query = request.Query ?? Query;
    }
}

src/Geta.NotFoundHandler.Admin/Areas/GetaNotFoundHandlerAdmin/Pages/Administer.cshtml
@page "{handler?}"
@model Geta.NotFoundHandler.Admin.Pages.Geta.NotFoundHandler.Admin.AdministerModel

@await Component.InvokeAsync("Card", new { message = Model.Message, cardType = Model.CardType })

<ul class="list-group list-group-flush">
    <li class="list-group-item">
        <form method="post">
            <div class="d-flex w-100 justify-content-between align-items-center">
                <div>Permanently delete all ignored suggestions</div>
                <button type="submit" class="btn btn-danger administer-button" data-confirm="Are you sure you wish to delete all ignored suggestions?"
                        asp-page-handler="DeleteAllIgnoredSuggestions">
                    <span data-feather="trash-2"></span> delete
                </button>
            </div>
        </form>
    </li>
    <li class="list-group-item">
        <form method="post">
            <div class="d-flex w-100 justify-content-between align-items-center">
                <div>Permanently delete all suggestions</div>
                <button type="submit" class="btn btn-danger administer-button" data-confirm="Are you sure you wish to delete all suggestions?"
                        asp-page-handler="DeleteAllSuggestions">
                    <span data-feather="trash-2"></span> delete
                </button>
            </div>
        </form>
    </li>
    <li class="list-group-item">
        <form method="post">
            <div class="d-flex w-100 justify-content-between align-items-center">
                <div>Permanently delete all custom redirects</div>
                <button type="submit" class="btn btn-danger administer-button" data-confirm="Are you sure you wish to delete all custom redirects?"
                        asp-page-handler="DeleteAllRedirects">
                    <span data-feather="trash-2"></span> delete
                </button>
            </div>
        </form>
    </li>
    <li class="list-group-item">
        <form method="post">
            <div class="d-flex w-100 justify-content-between">
                <div>
                    <div class="d-flex w-100 align-items-center">
                        Permanently delete all suggestions with less than
                        <input type="text" class="form-control input-number input-inline" asp-for="DeleteSuggestions.MaxErrors" value="@Model.DeleteSuggestions.MaxErrors">
                        <span asp-validation-for="DeleteSuggestions.MaxErrors" class="text-danger"></span>
                        error counts and older than
                        <input type="text" class="form-control input-number input-inline" asp-for="DeleteSuggestions.MinimumDays" value="@Model.DeleteSuggestions.MinimumDays">
                        <span asp-validation-for="DeleteSuggestions.MinimumDays" class="text-danger"></span>
                        days
                    </div>
                </div>
                <button type="submit" class="btn btn-danger administer-button" data-confirm="Are you sure you wish to delete these suggestions?"
                        asp-page-handler="DeleteSuggestions">
                    <span data-feather="trash-2"></span> delete
                </button>
            </div>
        </form>
    </li>
    <li class="list-group-item">
        <form method="post" enctype="multipart/form-data">
            <div class="d-flex w-100 justify-content-between">
                <div class="flex-fill">
                    <div class="d-flex w-100 align-items-center">
                        Import redirects from a valid XML or CSV
                        <input class="form-control ms-4 input-file" type="file" asp-for="ImportFile" accept=".xml, .csv">
                    </div>
                </div>
                <button type="submit" class="btn btn-primary administer-button"
                        asp-page-handler="ImportRedirects">
                    <span data-feather="upload"></span> import
                </button>
            </div>
        </form>
    </li>
    <li class="list-group-item">
        <form method="post" enctype="multipart/form-data">
            <div class="d-flex w-100 justify-content-between">
                <div class="flex-fill">
                    <div class="d-flex w-100 align-items-center">
                        Import Deleted(410) urls from a text file
                        <input class="form-control ms-4 input-file" type="file" asp-for="ImportFile" accept=".txt">
                    </div>
                </div>
                <button type="submit" class="btn btn-primary administer-button"
                        asp-page-handler="ImportDeletedRedirects">
                    <span data-feather="upload"></span> import
                </button>
            </div>
        </form>
    </li>
    <li class="list-group-item">
        <form method="post">
            <div class="d-flex w-100 justify-content-between align-items-center">
                <div>Export redirects to an XML-file</div>
                <button type="submit" class="btn btn-primary administer-button"
                        asp-page-handler="ExportRedirects">
                    <span data-feather="download"></span> export
                </button>
            </div>
            <input type="hidden" name="TypeId" value="xml">
        </form>
    </li>
    <li class="list-group-item">
        <form method="post">
            <div class="d-flex w-100 justify-content-between align-items-center">
                <div>Export redirects to an CSV-file</div>
                <button type="submit" class="btn btn-primary administer-button"
                        asp-page-handler="ExportRedirects">
                    <span data-feather="download"></span> export
                </button>
            </div>
            <input type="hidden" name="TypeId" value="csv">
        </form>
    </li>
</ul>

src/Geta.NotFoundHandler.Admin/Areas/GetaNotFoundHandlerAdmin/Pages/Ignored.cshtml
@page "{handler?}"
@using Geta.NotFoundHandler.Core.Redirects
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model Geta.NotFoundHandler.Admin.Pages.Geta.NotFoundHandler.Admin.IgnoredModel

@await Component.InvokeAsync("Card", new { message = Model.Message })

<form method="post">
    <div class="table-responsive mt-3">
        <table class="table table-hover table-sm" aria-label="Ignored redirects">
            <thead>
            <tr>
                <th>
                    <vc:sortable-header-cell key="@nameof(CustomRedirect.OldUrl)" display-name="URL"/>
                </th>
                <th class="col-1"></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.Items)
            {
                <tr class="align-middle">
                    <td>@item.OldUrl</td>
                    <td>
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-warning"
                                    asp-page-handler="unignore" asp-route-oldurl="@item.OldUrl">
                                <span data-feather="eye"></span> unignore
                            </button>
                        </div>
                    </td>
                </tr>
            }
            </tbody>
        </table>
        @await Component.InvokeAsync(typeof(Geta.NotFoundHandler.Admin.Pages.Geta.NotFoundHandler.Admin.Components.Pager.PagerViewComponent), new { Model.Items })
    </div>
</form>

src/Geta.NotFoundHandler.Admin/Areas/GetaNotFoundHandlerAdmin/Pages/Regex.cshtml
@page "{handler?}"
@using Geta.NotFoundHandler.Core.Providers.RegexRedirects
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model Geta.NotFoundHandler.Admin.Areas.Geta.NotFoundHandler.Admin.RegexModel

@await Component.InvokeAsync("Card", new { message = Model.Message })

<div class="table-responsive mt-3">
    <table class="table table-hover table-sm" aria-label="Redirects">
        <thead>
        <tr>
            <th class="col-1">
                <vc:sortable-header-cell key="@nameof(RegexRedirect.OrderNumber)" display-name="Order Number"/>
            </th>
            <th>
                <vc:sortable-header-cell key="@nameof(RegexRedirect.OldUrlRegex)" display-name="Old URL Regex"/>
            </th>
            <th>
                <vc:sortable-header-cell key="@nameof(RegexRedirect.NewUrlFormat)" display-name="New URL Format"/>
            </th>
            <th class="col-1"></th>
            <th class="col-1"></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <form method="post">
                <td>
                    <input type="text" class="form-control" asp-for="RegexRedirect.OrderNumber">
                    <span asp-validation-for="RegexRedirect.OrderNumber" class="text-danger"></span>
                </td>
                <td>
                    <input required type="text" class="form-control" asp-for="RegexRedirect.OldUrlRegex">
                    <span asp-validation-for="RegexRedirect.OldUrlRegex" class="text-danger"></span>
                </td>
                <td>
                    <input required type="text" class="form-control" asp-for="RegexRedirect.NewUrlFormat">
                    <span asp-validation-for="RegexRedirect.NewUrlFormat" class="text-danger"></span>
                </td>
                <td>
                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-primary"
                                asp-page-handler="create">
                            <span data-feather="plus"></span> add
                        </button>
                    </div>
                </td>
                <td></td>
            </form>
        </tr>

        @foreach (var item in Model.Items)
        {
            <tr class="align-middle">
                <td>@item.OrderNumber</td>
                <td>@item.OldUrlRegex</td>
                <td>@item.NewUrlFormat</td>
                <td>
                    @{
                        var editModalId = $"editModal{item.Id}";
                        var modalTitleId = $"modalTitle{item.Id}";
                    }

                    <div class="modal fade" id="@editModalId" tabindex="-1" aria-labelledby="@modalTitleId">
                        <div class="modal-dialog">
                            <div class="modal-content edit-modal">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="@modalTitleId">Edit</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <form method="post" id="form-@editModalId">
                                        <div class="input-group mb-2">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">Old URL Regex</span>
                                            </div>
                                            <textarea required class="form-control"
                                                      name="@Html.NameFor(m => m.EditRedirect.OldUrlRegex)" rows="1">@item.OldUrlRegex</textarea>
                                        </div>

                                        <span asp-validation-for="EditRedirect.OldUrlRegex"
                                              class="text-danger"></span>

                                        <div class="input-group mb-2">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">New URL Format</span>
                                            </div>
                                            <textarea required class="form-control"
                                                      name="@Html.NameFor(m => m.EditRedirect.NewUrlFormat)" rows="1">@item.NewUrlFormat</textarea>
                                        </div>

                                        <span asp-validation-for="EditRedirect.NewUrlFormat"
                                              class="text-danger"></span>

                                        <input type="hidden" asp-for="EditRedirect.Id" value="@item.Id"/>

                                        <div class="d-block mt-3">
                                            <button type="submit"
                                                    class="btn btn-primary"
                                                    asp-page-handler="update">Update
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="d-grid gap-2">
                        <button
                            type="submit"
                            class="btn btn-primary modal-trigger"
                            data-bs-toggle="modal"
                            data-bs-target="#@editModalId">
                            <span data-feather="edit"></span> edit
                        </button>
                    </div>

                </td>
                <td>
                    <div class="d-grid gap-2">
                        <form method="post">
                            <button type="submit" class="btn btn-danger"
                                    asp-page-handler="delete" asp-route-id="@item.Id">
                                <span data-feather="trash-2"></span> delete
                            </button> 
                        </form>
                    </div>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>